### ISSUE TITLE
Send Federated Consultation Summary - ITK3 Header page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#14] opened 2018-07-19 11:18 UTC
Just noticed at this point that MUST is used but on other pages SHALL is used. Assuming these are one in the same is best to stick to one or the other? Genuine question.

**Comment by briandiggle** [comment] 2018-08-16 14:08
Duplicate of #15

**Closed by briandiggle** 2018-08-16 14:08 UTC
