### ISSUE TITLE
Message receiver testing page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#35] opened 2018-07-23 08:47 UTC
Mixed used of terms for GP suppliers, suggest stick to GP principal clinical system suppliers or acronymised as PCS suppliers.
Like sneder testing page, suggest TODOs are removed or reworded as holding statements

**Comment by tim1ford** [comment] 2018-08-02 09:26
Duplicate of #26

**Closed by tim1ford** 2018-08-02 09:26 UTC
